### ISSUE TITLE
Support hostname change flow

### ISSUE THREAD

**Issue by yurem** [GluuFederation/super-gluu#11]
We need to add support for flow when we need to change hostname from `example1.host.name` to `example2.host.name` without forcing user to re-enroll devices.

This update requires changes in Gluu DB, Super Gluu Script parameters and Super Gluu Mobile application.
Here is list of required steps:
- Write script to update `dn: oxId=*,ou=fido,inum=*,ou=people,o=gluu` entries
  It should update `oxApplication` to replace `https://example1.host.name/identity/authcode.htm` to `https://example2.host.name/identity/authcode.htm`
- Update `Super Gluu` script parameter `registration_uri` to point to new hostname
- Add new option `Allow hostname update` to Super Gluu. It should be off by default. If this option is on application should update enrolled entry in application DB to update new hostname and turn off this option after that. Now it throws exception due to hostname mismatch.

**Comment by NazarYavornytskyy** [comment]
Done
