### ISSUE TITLE
fix: key stored even if enrollment is denied

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/super-gluu#24]
When hitting "deny" on an attempt to enroll results in a new key stored in the app

While the enrollment is not stored in server, this prevents subsequent enrollments to succeed

**Comment by NazarYavornytskyy** [comment]
PR is ready - https://github.com/GluuFederation/super-gluu/pull/27

**Comment by jgomer2001** [comment]
thanks, closing then
