### ISSUE TITLE
Android: 2nd Device Authn Fails

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/super-gluu#5]
1. Register Phone 1
2. Register Phone 2
3. Logout 
4. Login -- both phones get push notificaition
5. Approve on Phone 2

Result: `FIDO U2F response was rejected` 

If I delete Phone 1 in Casa, and authn, it succeeds.

**Comment by jsmith-clearsense** [comment]
Is there any update on this? This is a very frustrating bug.

**Comment by nynymike** [comment]
We are about to push a new package. Sorry it took so long. We had to update for some underlying libraries to comply with Play Store requirements.

**Comment by jsmith-clearsense** [comment]
Awesome, thanks for the update!

**Comment by nynymike** [comment]
This is resolved with the latest build.
