### ISSUE TITLE
Android Keys are not deleted

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/super-gluu#6]
1. View Keys
2. Delete Key
3. Stop app 
4. Start app

Result: Key appears again... it wasn't really deleted.

**Comment by NazarYavornytskyy** [comment]
@nynymike tested Latest Android app, cannot reproduce this issue. Can you give more details or even record a video of the issue.

**Comment by nynymike** [comment]
Even if I delete the keys in Super Gluu, delete the storage for the app, and uninstall... when I reinstall super Gluu, my keys are still there.

**Comment by NazarYavornytskyy** [comment]
I guess, this issue is gone, indeed?

**Comment by NazarYavornytskyy** [comment]
Verified on latest build - seems issue is gone
