### ISSUE TITLE
Timeout Notification / Cancel

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/super-gluu#7]
Both the notification or the login screen should timeout after 60 seconds. I found this note on how to timeout the notification in Android: https://stackoverflow.com/questions/23874203/create-an-android-notification-with-expiration-date 

Having old notifications (days later) degrades security. 

Also, there should be a cancel on the authn approval screen. For example, what if I have two phones, and I want to cancel out of the authn screen on one phone (but not DENY). 

Equally weird is when I left swipe to "go back in my app", the in-app notification disappears. But then it comes back when I re-open the app. 

Net-net, the cancel / timeout behavior is really confusing.

**Comment by NazarYavornytskyy** [comment]
Timeout clock is disabled at the moment. Also you can easy close Approve/Deny screen - no need to wait anymore

**Comment by nynymike** [comment]
![super-gluu-msg](https://user-images.githubusercontent.com/3717101/182685775-dd9f805e-89b8-46a3-8a88-038b6cd4f6b2.jpg)

How do you cancel? 

The timeout was too short... 30 seconds. The background notify **never** disappears.

**Comment by NazarYavornytskyy** [comment]
Probably you can click Back button on bottom on your Android device - default Android behavior to back to previous screen. Should work here as well

**Comment by nynymike** [comment]
It does not work well. The notification comes back up when I restart the app. Also, it is not obvious that I should hit the back button... there should be a cancel. Let's have an offline discussion about this after the current release is out... because the current cancel/timeout usability is a mess.

**Comment by NazarYavornytskyy** [comment]
Turned it off for current release

**Comment by christian-hawk** [comment]
@NazarYavornytskyy is this issue solved? If yes, may you link to the commit/PR, if there is any?

**Comment by NazarYavornytskyy** [comment]
@christian-hawk done for Android, going to do the same for iOS

**Comment by NazarYavornytskyy** [comment]
@christian-hawk PR is ready - https://github.com/GluuFederation/super-gluu/pull/21

**Comment by christian-hawk** [comment]
good job, thanks @NazarYavornytskyy
