### ISSUE TITLE
Upgrade Logging

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/super-gluu#8]
In the Android app, when you view the list of logs, there is an EDIT button which enables you to select multiple logs, and then DELETE THEM. The problem is, nothing happens when you hit DELETE. Also, should the initial link really say EDIT? Shouldn't it say 
"Bulk Select" or even just "Select"? And it would be nice if there was a checkbox to "Select all" Or clear all logs.

**Comment by NazarYavornytskyy** [comment]
https://github.com/GluuFederation/super-gluu/commit/ec606afc472c21819673f8b655e67aa92134c3cf
