### ISSUE TITLE
Update Error Messages

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/super-gluu#9]
The messages displayed to the end user should never mention `FIDO` or `FIDO U2F` or include stacktraces or technical jargon. If there are geeky messages, save them to a log file that the end user can share with the system admin. But the messages to the end user should be high level, and tell when specifically the error occured, i.e. failed to authenticate, failed to enroll, failed to connect to... etc.

**Comment by NazarYavornytskyy** [comment]
So, we have next error messages contains FIDO word:
<string name="wrong_u2f_metadata">Failed to get Fido U2F metadata</string>
    <string name="failed_process_challenge">Fido U2F challenge was rejected</string>
    <string name="wrong_token_response">Fido U2F token response is invalid</string>
    <string name="failed_process_response">Fido U2F response was rejected</string>
    <string name="failed_process_status">Get unexpected Fido U2F status</string>
    <string name="process_u2f_request">Processing Fido U2F request, please wait…</string>

**Comment by nynymike** [comment]
| Olds        | New           | 
| ------------- |:-------------:| 
|Failed to get Fido U2F metadata | Failed to connect to Server| 
|Fido U2F challenge was rejected | Authentication challenge rejected|
|Fido U2F token response is invalid | Authentication token response invalid|
|Fido U2F response was rejected | Authentication response rejected|
|Get unexpected Fido U2F status | Unexpected authentication response|
|Processing Fido U2F request, please wait… | Authenticating, please wait...|

**Comment by NazarYavornytskyy** [comment]
https://github.com/GluuFederation/super-gluu/commit/3b6cadf867fbc0b1630c88670f7f27b0dad14d31
